// Generated by scripts/build-pi-demo.mjs from the public research example.
export const demoData = {
  "workflow": {
    "v": 2,
    "name": "deep-research",
    "schemas": {
      "Question": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "question": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "question"
        ],
        "additionalProperties": false
      },
      "Plan": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "questions": {
            "minItems": 1,
            "maxItems": 5,
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "required": [
          "questions"
        ],
        "additionalProperties": false
      },
      "Finding": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "question": {
            "type": "string"
          },
          "answer": {
            "type": "string"
          },
          "sources": {
            "minItems": 1,
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "text": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "text"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "question",
          "answer",
          "sources"
        ],
        "additionalProperties": false
      },
      "Report": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "answer": {
            "type": "string"
          },
          "findings": {
            "minItems": 1,
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "question": {
                  "type": "string"
                },
                "answer": {
                  "type": "string"
                },
                "sources": {
                  "minItems": 1,
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "text": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "text"
                    ],
                    "additionalProperties": false
                  }
                }
              },
              "required": [
                "question",
                "answer",
                "sources"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "answer",
          "findings"
        ],
        "additionalProperties": false
      }
    },
    "input": {
      "schemaId": "Question"
    },
    "output": {
      "schemaId": "Report",
      "path": "report"
    },
    "root": {
      "node": "chain",
      "steps": [
        {
          "node": "decide",
          "label": "plan",
          "instructions": "Break the research question into up to five distinct, answerable subquestions. Each runs independently: include its subject and relevant context so it makes sense without the original question.",
          "state": {
            "question": "{question}"
          },
          "out": "Plan",
          "as": "plan"
        },
        {
          "node": "map",
          "label": "research",
          "itemsPath": "plan.questions",
          "as": "findings",
          "maxConcurrency": 3,
          "resultPath": "finding",
          "body": {
            "node": "workflow",
            "label": "research-question",
            "workflow": {
              "v": 2,
              "name": "research-one-question",
              "schemas": {
                "Question": {
                  "$schema": "http://json-schema.org/draft-07/schema#",
                  "type": "object",
                  "properties": {
                    "question": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "question"
                  ],
                  "additionalProperties": false
                },
                "Sources": {
                  "$schema": "http://json-schema.org/draft-07/schema#",
                  "type": "object",
                  "properties": {
                    "sources": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "text": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "id",
                          "text"
                        ],
                        "additionalProperties": false
                      }
                    }
                  },
                  "required": [
                    "sources"
                  ],
                  "additionalProperties": false
                },
                "Finding": {
                  "$schema": "http://json-schema.org/draft-07/schema#",
                  "type": "object",
                  "properties": {
                    "question": {
                      "type": "string"
                    },
                    "answer": {
                      "type": "string"
                    },
                    "sources": {
                      "minItems": 1,
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "text": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "id",
                          "text"
                        ],
                        "additionalProperties": false
                      }
                    }
                  },
                  "required": [
                    "question",
                    "answer",
                    "sources"
                  ],
                  "additionalProperties": false
                },
                "EvidenceDecision": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "answersQuestion"
                  ],
                  "properties": {
                    "answersQuestion": {
                      "type": "boolean",
                      "description": "Does this candidate passage provide concrete information for answering `subquestion`? Evaluate the passage's claims, not keyword overlap. A partial answer, a condition, a limitation, or evidence contradicting the proposed answer counts; the passage need not settle the whole question.",
                      "criteria": {
                        "true": "Reports a specific fact, observation, rule or limitation bearing on the subquestion. Keep supporting and contrary evidence, including qualified answers; do not require proof that the answer holds in every situation.",
                        "false": "Only mentions the topic, promises an unspecified benefit, omits the information needed to bear on the subquestion, or describes a different subject without establishing relevance."
                      }
                    }
                  }
                }
              },
              "input": {
                "schemaId": "Question"
              },
              "output": {
                "schemaId": "Finding",
                "path": "finding"
              },
              "root": {
                "node": "chain",
                "steps": [
                  {
                    "node": "call",
                    "label": "search",
                    "via": "tool",
                    "tool": "search",
                    "args": {
                      "question": "{question}"
                    },
                    "out": "Sources",
                    "as": "search",
                    "deadline_s": 15
                  },
                  {
                    "node": "sift",
                    "label": "screen-evidence",
                    "itemsPath": "search.sources",
                    "state": {
                      "subquestion": "{question}"
                    },
                    "out": "EvidenceDecision",
                    "as": "evidence",
                    "keep": {
                      "path": "answersQuestion",
                      "gte": 0.8
                    }
                  },
                  {
                    "node": "escalate",
                    "label": "missing-evidence",
                    "when": {
                      "predicate": "empty",
                      "path": "evidence.items"
                    },
                    "kind": "needs_research",
                    "stage": "evidence",
                    "summary": "No selected evidence addresses: {question}"
                  },
                  {
                    "node": "agent",
                    "label": "write-finding",
                    "instructions": "Answer this subquestion using only the selected sources. Preserve contrary evidence, conditions and uncertainty. Say what cannot be determined when evidence is partial; do not turn a conditional claim into an unconditional conclusion. Return the question, answer and cited source records.",
                    "state": {
                      "question": "{question}",
                      "sources": "{evidence.items}"
                    },
                    "out": "Finding",
                    "as": "finding"
                  }
                ]
              }
            },
            "input": {
              "question": "{item}"
            },
            "out": "Finding",
            "as": "finding"
          }
        },
        {
          "node": "agent",
          "label": "write-report",
          "instructions": "Answer the original question from these findings. Preserve disagreements, conditions, uncertainty and remaining limitations. Keep unresolved questions explicit; do not present partial findings as conclusive.",
          "state": {
            "question": "{question}",
            "findings": "{findings}"
          },
          "out": "Report",
          "as": "report"
        }
      ]
    }
  },
  "question": "Should our small team move its documentation from a wiki into the code repository?",
  "sources": [
    {
      "id": "review-guide",
      "text": "In this fictional team, documentation changes in the repository require a pull request and an assigned reviewer."
    },
    {
      "id": "advert",
      "text": "Repository documentation will transform your whole business."
    },
    {
      "id": "editor-trial",
      "text": "In the fictional trial, browser editing worked, but two non-developers needed help resolving merge conflicts."
    },
    {
      "id": "design-news",
      "text": "The wiki product has changed its logo."
    },
    {
      "id": "search-trial",
      "text": "The fictional repository search found filenames and exact words, but missed the synonyms people used in the wiki."
    },
    {
      "id": "search-advert",
      "text": "Find anything instantly with our new search experience."
    }
  ],
  "subquestions": [
    "What review process would our team use for documentation changes in the code repository?",
    "Can our team’s non-developers edit documentation in the code repository?",
    "How does documentation search in the code repository compare with our wiki?"
  ],
  "evidenceIds": [
    "review-guide",
    "editor-trial",
    "search-trial"
  ]
};
