// The native package ships the same research definition as the repository demo.
import { writeFile } from 'node:fs/promises';
import { deepResearch } from '../examples/typed-research.ts';
import { question, sourceSets, subquestions } from '../examples/typed-research-fixtures.ts';
const data = { workflow: deepResearch, question, sources: sourceSets.flat(), subquestions, evidenceIds: sourceSets.map(set => set[0].id) };
await writeFile(new URL('../packages/pi/src/demo-data.ts', import.meta.url), '// Generated by scripts/build-pi-demo.mjs from the public research example.\nexport const demoData = ' + JSON.stringify(data, null, 2) + ';\n');
