#!/usr/bin/env node
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { chmod, lstat, mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, join, posix, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const arguments_ = process.argv.slice(2);
assert.ok(arguments_.length <= 1 && arguments_.every(argument => ['--inventory-only'].includes(argument)), 'Usage: node scripts/export-source.mjs [--inventory-only]');
const release = join(root, '.release');
const destination = join(release, 'agentrun-dsl-source');
const staging = join(release, `.source-staging-${process.pid}`);
const archive = join(release, 'agentrun-dsl-source.tar.gz');
const exec = promisify(execFile);
const sha256 = value => createHash('sha256').update(value).digest('hex');
const lockBytes = await readFile(join(root, 'package-lock.json'));
const lock = JSON.parse(lockBytes);
assert.equal(lock.lockfileVersion, 3, 'Source inventory requires package-lock v3');

// Resolve the lockfile graph using package-local dependencies before hoisted dependencies.
// Include optional packages and peers even when the current OS does not install their binaries.
const entries = lock.packages;
const roots = ['dsl', 'jev', 'pi'];
const inventory = new Map();
const unresolved = [];
function resolveDependency(from, name) {
  for (let directory = from; ; directory = posix.dirname(directory)) {
    const candidate = posix.join(directory === '.' ? '' : directory, 'node_modules', name);
    if (entries[candidate]) return entries[candidate].link ? entries[candidate].resolved : candidate;
    if (!directory || directory === '.') return null;
  }
}
for (const consumer of roots) {
  const seen = new Set();
  const visit = location => {
    if (seen.has(location)) return;
    seen.add(location);
    const pkg = entries[location];
    assert.ok(pkg, `Missing lockfile package ${location}`);
    if (location.startsWith('node_modules/')) {
      const name = pkg.name ?? location.slice(location.lastIndexOf('node_modules/') + 'node_modules/'.length);
      const key = `${name}@${pkg.version}`;
      const row = inventory.get(key) ?? { name, version: pkg.version, license: pkg.license ?? 'UNKNOWN', consumers: new Set(), locations: new Set(), optional: true };
      assert.equal(row.license, pkg.license ?? 'UNKNOWN', `Conflicting license metadata for ${key}`);
      row.consumers.add(consumer); row.locations.add(location); row.optional &&= pkg.optional === true;
      inventory.set(key, row);
    }
    const dependencies = new Set([...Object.keys(pkg.dependencies ?? {}), ...Object.keys(pkg.optionalDependencies ?? {}), ...Object.keys(pkg.peerDependencies ?? {})]);
    for (const dependency of dependencies) {
      const target = resolveDependency(location, dependency);
      if (!target) {
        const optional = Object.hasOwn(pkg.optionalDependencies ?? {}, dependency) || pkg.peerDependenciesMeta?.[dependency]?.optional === true;
        unresolved.push({ from: location, dependency, optional, consumer });
        assert.ok(optional, `Required runtime dependency absent from lockfile: ${location} -> ${dependency}`);
      } else visit(target);
    }
  };
  visit(`packages/${consumer}`);
}
const rows = [...inventory.values()].sort((a, b) => `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`)).map(row => ({ ...row, consumers: [...row.consumers].sort(), locations: [...row.locations].sort() }));
const permissive = new Set(['MIT', 'Apache-2.0', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC', '0BSD', 'BlueOak-1.0.0', 'CC0-1.0', 'Unlicense']);
const flagged = rows.filter(row => !permissive.has(row.license)).map(row => ({ name: row.name, version: row.version, license: row.license, reason: row.license === 'UNKNOWN' ? 'Missing license metadata' : /GPL|AGPL|LGPL|SSPL|BUSL|BSL|UNLICENSED/i.test(row.license) ? 'Restrictive or reciprocal metadata needs release-owner review' : 'License expression needs release-owner review' }));
const missingOptional = [...new Map(unresolved.map(item => [`${item.from}:${item.dependency}`, item])).values()];
const licenses = [...new Set(rows.map(row => row.license))].sort();
const cell = value => String(value).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const dependencyDoc = `# Runtime dependency inventory

Generated by \`node scripts/export-source.mjs\` from \`package-lock.json\` (SHA-256 \`${sha256(lockBytes)}\`). Regenerate after dependency changes.

The graph starts from the runtime dependencies of \`@parcha/agentrun-dsl\`, \`@parcha/agentrun-jev\`, and \`@parcha/agentrun-pi\`, follows their dependencies and peers, and includes optional platform packages recorded in the lockfile. Development-only tooling is excluded. Versions are the exact locked versions, not the ranges in package manifests. “Optional” identifies entries marked optional at every recorded installation location; package use still depends on platform and adapter configuration.

${rows.length} distinct third-party package/version pairs across ${rows.reduce((sum, row) => sum + row.locations.length, 0)} lockfile locations. Declared licenses: ${licenses.map(value => `\`${value}\``).join(', ')}.

## Release review

${flagged.length ? flagged.map(row => `- **${cell(row.name)}@${cell(row.version)}:** ${cell(row.license)} — ${row.reason}.`).join('\n') : 'No missing, restrictive, reciprocal, or unrecognized license identifiers were found in this runtime lockfile graph.'}

AgentRun's own license is declared in its package manifests, separately from this third-party inventory. This table records package metadata, not an approval to redistribute. The release owner must confirm source rights, inspect applicable license texts, and preserve required notices.

${missingOptional.length ? `Optional peer/dependency names absent from this lockfile: ${missingOptional.map(row => `\`${row.dependency}\``).join(', ')}. These are not counted as inventoried packages; adding them requires regenerating this inventory.\n` : 'All runtime dependency and peer names resolve within the lockfile, including optional entries.\n'}
## Locked packages

| Package | Version | Declared license | Used by | Optional | Lock locations |
| --- | --- | --- | --- | --- | --- |
${rows.map(row => `| ${cell(row.name)} | ${cell(row.version)} | ${cell(row.license)} | ${row.consumers.join(', ')} | ${row.optional ? 'yes' : 'no'} | ${row.locations.length} |`).join('\n')}
`;
await writeFile(join(root, 'docs/dependencies.md'), dependencyDoc);
if (arguments_.includes('--inventory-only')) {
  console.log(`Dependency inventory updated: ${rows.length} locked runtime package/version pairs.`);
  process.exit(0);
}

const allowedRootFiles = new Set(['README.md', 'CHANGELOG.md', 'CONTRIBUTING.md', 'SECURITY.md', 'ASSETS.md', 'LICENSE', 'LICENSE.md', 'LICENSE.txt', 'NOTICE', 'NOTICE.md', 'NOTICE.txt', '.gitignore', '.nvmrc', 'package.json', 'package-lock.json', 'tsconfig.base.json']);
const allowedDirectories = new Set(['docs', 'examples', 'packages', 'scripts', 'spec', '.github']);
const excludedComponents = new Set(['site', 'dist', 'node_modules', '.git', '.release', '.openai', '.sites-runtime', '.cascade', '.desloppify', '.impeccable', '.review', '.reviews', '.codex', '.agents', '.cache', 'coverage', 'candidates', 'scorecard.png', '.lake']);
const textExtensions = new Set(['.md', '.json', '.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.html', '.css', '.svg', '.txt', '.yml', '.yaml', '.toml', '.sh', '.lean']);
const binaryExtensions = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif', '.ico', '.woff', '.woff2', '.webm']);
function extension(path) { const leaf = path.split('/').at(-1); return leaf.includes('.') ? leaf.slice(leaf.lastIndexOf('.')).toLowerCase() : ''; }
function excluded(path) {
  const parts = path.split('/');
  return parts.some(part => part === 'pi.config.mjs' || excludedComponents.has(part) || /(?:^|\.)review(?:\.|$)/.test(part) || /^\.env(?:\.|$)/.test(part) || /(?:^|\.)local(?:\.|$)/.test(part)) ||
    /\.(?:tgz|tar|gz|pem|key|p12|pfx|map|log)$/.test(path);
}
const forbidden = [
  ['machine_path', /\/(?:home|Users)\/[A-Za-z0-9._-]+\//],
  ['internal_domain', /(?:[a-z0-9.-]+\.)?(?:code\.run|northflank\.com|ts\.net)\b/i],
  ['private_key', /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/],
  ['github_token', /\b(?:gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{40,})\b/],
  ['provider_secret', /\bsk-(?:proj-|ant-api\d+-)?[A-Za-z0-9_-]{30,}\b/],
  ['aws_access_key', /\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/],
  ['credential_url', /https?:\/\/[^\s/:]+:[^\s/@]+@/],
  ['bearer_secret', /\bBearer\s+[A-Za-z0-9._-]{24,}/],
  ['literal_credential', /(?:api[_-]?key|password|access[_-]?token|auth[_-]?token|client[_-]?secret)['"]?\s*[=:]\s*['"][^'"\n]{8,}['"]/i],
];
const findings = [], reviewed = [], files = [];
function scan(path, content) {
  const lines = content.split('\n');
  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    const decoded = line.replace(/(?:%[0-9a-f]{2})+/gi, value => { try { return decodeURIComponent(value); } catch { return value; } });
    for (const [rule, pattern] of forbidden) {
      const expression = new RegExp(pattern.source, pattern.flags.includes('g') ? pattern.flags : pattern.flags + 'g');
      const matches = new Set([...line.matchAll(expression), ...(decoded === line ? [] : decoded.matchAll(expression))].map(match => match[0]));
      for (const matched of matches) {
        const proof = { path, line: index + 1, rule, lineSha256: sha256(line) };
        // Public examples/tests may use explicit fake credentials, never plausible secrets.
        const fakeCredential = rule === 'literal_credential' && /^(?:api[_-]?key|password|access[_-]?token|auth[_-]?token|client[_-]?secret)['"]?\s*[=:]\s*['"](?:fake-test-key|fake|test-key|example|your-key|YOUR_[A-Z_]+|not-a-secret)['"]$/i.test(matched);
        if (fakeCredential) reviewed.push({ ...proof, reason: 'Explicit fake/example credential literal.' });
        else findings.push(proof);
      }
    }
  }
}
async function collect(relative = '') {
  for (const entry of (await readdir(join(root, relative), { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
    const path = relative ? `${relative}/${entry.name}` : entry.name;
    if (excluded(path)) continue;
    if (!relative && !(entry.isDirectory() ? allowedDirectories.has(entry.name) : allowedRootFiles.has(entry.name))) continue;
    if (entry.isSymbolicLink()) throw new Error(`Source export refuses symlink: ${path}`);
    if (entry.isDirectory()) { await collect(path); continue; }
    if (!entry.isFile()) throw new Error(`Source export refuses special file: ${path}`);
    const ext = extension(path);
    const isText = entry.name === '.gitignore' || textExtensions.has(ext) || allowedRootFiles.has(path) || /^packages\/(?:dsl|jev|pi)\/(?:LICENSE|NOTICE)$/.test(path) || path === 'spec/lean/lean-toolchain';
    if (!isText && !binaryExtensions.has(ext)) throw new Error(`Unreviewed source-export file type: ${path}`);
    const bytes = await readFile(join(root, path));
    if (isText) {
      const content = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
      assert.ok(!content.includes('\0'), `NUL byte in expected text file: ${path}`);
      scan(path, content);
    }
    files.push({ path, bytes, sha256: sha256(bytes), size: bytes.length, kind: isText ? 'text' : 'binary' });
  }
}
const receipt = {
  status: 'running', publicationReady: false, generatedAt: new Date().toISOString(), node: process.version,
  packageLockSha256: sha256(lockBytes), exclusions: [...excludedComponents, '*.review.*', '.env*', '*.local.*', 'archives', 'source maps', 'logs', 'key files'],
  limitations: ['Heuristic scanning cannot prove the absence of every secret or private fact.', 'Binary assets are hashed and allowlisted by extension, not semantically inspected.', 'Export success does not authorize publication; source provenance, license and owner approval remain required.'],
  runtimeDependencies: { count: rows.length, packages: rows, flags: flagged, unresolvedOptional: missingOptional },
};
await mkdir(release, { recursive: true });
try {
  await collect();
  assert.ok(files.some(file => file.path === 'packages/dsl/schema/workflow.schema.json'), 'Generate the workflow schema before exporting source');
  receipt.findings = findings; receipt.reviewedFindings = reviewed;
  if (findings.length) throw new Error(`Source export blocked by ${findings.length} unreviewed finding(s); see .release/source-export-receipt.json (content omitted)`);
  await rm(staging, { recursive: true, force: true });
  await mkdir(staging);
  for (const file of files) {
    const target = join(staging, file.path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, file.bytes, { mode: 0o644 });
    await chmod(target, 0o644);
    assert.equal(sha256(await readFile(target)), file.sha256, `Export byte mismatch: ${file.path}`);
    assert.ok((await lstat(target)).isFile(), `Export is not a regular file: ${file.path}`);
  }
  await rm(destination, { recursive: true, force: true });
  await rename(staging, destination);
  await exec('tar', ['--sort=name', '--mtime=@0', '--owner=0', '--group=0', '--numeric-owner', '-czf', archive, '-C', release, 'agentrun-dsl-source'], { maxBuffer: 16 * 1024 * 1024 });
  const archiveBytes = await readFile(archive);
  const listing = (await exec('tar', ['-tzf', archive], { maxBuffer: 16 * 1024 * 1024 })).stdout.trim().split('\n').filter(name => !name.endsWith('/'));
  assert.deepEqual(listing.map(name => name.replace(/^agentrun-dsl-source\//, '')).sort(), files.map(file => file.path).sort(), 'Archive file inventory differs from reviewed source');
  receipt.files = files.map(({ bytes, ...metadata }) => metadata).sort((a, b) => a.path.localeCompare(b.path));
  receipt.sourceTreeSha256 = sha256(receipt.files.map(file => `${file.path}\0${file.sha256}\n`).join(''));
  receipt.archive = { path: '.release/agentrun-dsl-source.tar.gz', sha256: sha256(archiveBytes), size: archiveBytes.length };
  receipt.status = 'passed';
  console.log(`Source export passed: ${files.length} files; ${rows.length} locked runtime package/version pairs; ${flagged.length} dependency license flags.`);
  console.log('Receipt: .release/source-export-receipt.json. Export validation does not authorize publication.');
} catch (error) {
  receipt.status = 'failed'; receipt.error = error instanceof Error ? error.message : 'Unknown export failure';
  console.error(receipt.error); process.exitCode = 1;
} finally {
  await writeFile(join(release, 'source-export-receipt.json'), JSON.stringify(receipt, null, 2) + '\n');
  await rm(staging, { recursive: true, force: true });
}
